---
name: kics
on:
  pull_request:
    branches: ["master"]

jobs:
  kics:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        name: Check out source code

      - name: run a KICS scan
        uses: checkmarx/kics-github-action@c456d047c6b73a360a5e1deb892e3f90fa372a04
        with:
          path: .
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: myResults/
